package orthocal

import (
	"regexp"
	"strings"
)

var BookNames = map[string]string{
	// Old Testament
	"gen":             "Бут.",
	"genesis":         "Бут.",
	"бут":             "Бут.",
	"буття":           "Бут.",
	"exod":            "Вих.",
	"exodus":          "Вих.",
	"lev":             "LEV",
	"leviticus":       "LEV",
	"num":             "NUM",
	"numbers":         "NUM",
	"deut":            "DEU",
	"deuteronomy":     "DEU",
	"josh":            "JOS",
	"joshua":          "JOS",
	"judges":          "JDG",
	"judg":            "JDG",
	"ruth":            "RUT",
	"1 kgs":           "1SA",
	"1 kings":         "1SA",
	"2 kgs":           "2SA",
	"2 kings":         "2SA",
	"3 kgs":           "1KI",
	"3 kings":         "1KI",
	"4 kgs":           "2KI",
	"4 kings":         "2KI",
	"1 chr":           "1CH",
	"1 chronicles":    "1CH",
	"2 chr":           "2CH",
	"2 chronicles":    "2CH",
	"ezra":            "EZR",
	"neh":             "NEH",
	"nehemiah":        "NEH",
	"esth":            "EST",
	"esther":          "EST",
	"job":             "JOB",
	"ps":              "PSA",
	"psalm":           "PSA",
	"psalms":          "PSA",
	"prov":            "PRO",
	"proverbs":        "PRO",
	"eccl":            "ECC",
	"ecclesiastes":    "ECC",
	"song":            "SNG",
	"song of solomon": "SNG",
	"song of songs":   "SNG",
	"isa":             "ISA",
	"isaiah":          "ISA",
	"jer":             "JER",
	"jeremiah":        "JER",
	"hos":             "HOS",
	"hosea":           "HOS",
	"joel":            "JOL",
	"amos":            "AMO",
	"obad":            "OBA",
	"obadiah":         "OBA",
	"jonah":           "JON",
	"jon":             "JON",
	"mic":             "MIC",
	"micah":           "MIC",
	"nah":             "NAM",
	"nahum":           "NAM",
	"hab":             "HAB",
	"habakkuk":        "HAB",
	"zech":            "ZEC",
	"zechariah":       "ZEC",
	"hag":             "HAG",
	"hagai":           "HAG",
	"lam":             "LAM",
	"lamentations":    "LAM",
	"ezek":            "EZK",
	"ezekiel":         "EZK",
	"dan":             "DAN",
	"daniel":          "DAN",
	"zeph":            "ZEP",
	"zephaniah":       "ZEP",
	"mal":             "MAL",
	"malachi":         "MAL",

	// Deuterocanonical
	"tobit":                  "TOB",
	"tob":                    "TOB",
	"judith":                 "JDT",
	"additions to esther":    "ESG",
	"wis":                    "WIS",
	"wisdom":                 "WIS",
	"wisdom of solomon":      "WIS",
	"sirach":                 "SIR",
	"ecclesiasticus":         "SIR",
	"wisdom of sirach":       "SIR",
	"baruch":                 "BAR",
	"letter of jeremiah":     "LJE",
	"song of the three":      "S3Y",
	"prayer of azariah":      "S3Y",
	"susanna":                "SUS",
	"bel and the dragon":     "BEL",
	"1 maccabees":            "1MA",
	"2 maccabees":            "2MA",
	"3 maccabees":            "3MA",
	"4 maccabees":            "4MA",
	"1 esdras":               "1ES",
	"2 esdras":               "2ES",
	"manasseh":               "MAN",
	"the prayer of manasseh": "MAN",

	// New Testament
	"matt":            "Мф.",
	"matthew":         "Мф.",
	"mt":              "Мф.",
	"мф":              "Мф.",
	"матфея":          "Мф.",
	"mark":            "Мк.",
	"mk":              "Мк.",
	"марка":           "Мк.",
	"мк":              "Мк.",
	"luke":            "Лк.",
	"lk":              "Лк.",
	"луки":            "Лк.",
	"лк":              "Лк.",
	"john":            "Ін.",
	"jn":              "Ін.",
	"Іоана":           "Ін.",
	"ін":              "Ін.",
	"acts":            "Діян.",
	"діян":            "Діян.",
	"діяння":          "Діян.",
	"rom":             "Рим.",
	"римлян":          "Рим.",
	"рим":             "Рим.",
	"1 cor":           "1Кор.",
	"1 corinthians":   "1Кор.",
	"1 кор":           "1Кор.",
	"1 коринф'ян":     "1Кор.",
	"2 cor":           "2Кор.",
	"2 corinthians":   "2Кор.",
	"2 кор":           "2Кор.",
	"2 коринф'ян":     "2Кор.",
	"1 thess":         "1Сол.",
	"1 thessalonians": "1Сол.",
	"1 сол":           "1Сол.",
	"1 солунян":       "1Сол.",
	"2 thess":         "2Сол.",
	"2 thessalonians": "2Сол.",
	"2 сол":           "2Сол.",
	"2 солунян":       "2Сол.",
	"gal":             "Гал.",
	"galatians":       "Гал.",
	"гал":             "Гал.",
	"галатів":         "Гал.",
	"eph":             "Еф.",
	"ephesians":       "Еф.",
	"еф":              "Еф.",
	"ефесян":          "Еф.",
	"phil":            "Флп.",
	"philippians":     "Флп.",
	"флп":             "Флп.",
	"филип'ян":        "Флп.",
	"col":             "Кол.",
	"colosians":       "Кол.",
	"кол":             "Кол.",
	"колосян":         "Кол.",
	"1 tim":           "1Тим.",
	"1 timothy":       "1Тим.",
	"1 тим":           "1Тим.",
	"1 тимофія":       "1Тим.",
	"2 tim":           "2Тим.",
	"2 timothy":       "2Тим.",
	"2 тим":           "2Тим.",
	"2 тимофія":       "2Тим.",
	"1 john":          "1Ін.",
	"1 jn":            "1Ін.",
	"1 ін":            "1Ін.",
	"1 іоана":         "1Ін.",
	"2 john":          "2Ін.",
	"2 jn":            "2Ін.",
	"2 ін":            "2Ін.",
	"2 іоана":         "2Ін.",
	"3 john":          "3Ін.",
	"3 jn":            "3Ін.",
	"3 ін":            "3Ін.",
	"3 іона":          "3Ін.",
	"1 pet":           "1Пет.",
	"1 peter":         "1Пет.",
	"1 пет":           "1Пет.",
	"1 петра":         "1Пет.",
	"2 pet":           "2Пет.",
	"2 peter":         "2Пет.",
	"2 петра":         "2Пет.",
	"2 пет":           "2Пет.",
	"heb":             "Євр.",
	"hebrews":         "Євр.",
	"євреїв":          "Євр.",
	"євр":             "Євр.",
	"тита":            "Тит.",
	"тит":             "Тит.",
	"philemon":        "Фил.",
	"phlm":            "Фил.",
	"фил":             "Фил.",
	"филимона":        "Фил.",
	"jas":             "Як.",
	"james":           "Як.",
	"як":              "Як.",
	"якова":           "Як.",
	"jude":            "Іуд.",
	"іуди":            "Іуд.",
	"іуд":             "Іуд.",
	"rev":             "Одкр.",
	"revelation":      "Одкр.",
	"одкр":            "Одкр.",
	"одкровення":      "Одкр.",
}

func NormalizeBookName(name string) string {
	name = regexp.MustCompile(`\s+`).ReplaceAllLiteralString(name, " ")
	name = strings.Replace(name, ".", "", -1)
	name = strings.Trim(name, " ")
	name = strings.ToLower(name)
	if normalized, ok := BookNames[name]; ok {
		return normalized
	} else {
		return ""
	}
}
